<?php
/**
 * Privacy Policy.
 *
 * Describes only what the site actually collects: the enquiry form, the
 * checkout form, the account tables and the PHP session cookie. If a new
 * tracker or third-party script is ever added to the site, the "What we
 * collect" and "Cookies" sections below have to be updated with it.
 */
require_once __DIR__ . '/includes/functions.php';

$page_title     = 'Privacy Policy | Fabloom Group of Company';
$page_desc      = 'How Fabloom collects, uses, stores and protects the personal information you share through our enquiry forms, orders and account pages.';
$page_canonical = SITE_URL . '/privacy-policy';

$legal_eyebrow = 'Your Data, Your Rights';
$legal_title   = 'Privacy Policy';
$legal_sub     = 'What we collect when you enquire or order, why we collect it, and how you can have it corrected or removed.';
$legal_crumb   = 'Privacy Policy';

$page_schema = json_encode([
    '@context' => 'https://schema.org',
    '@graph'   => [
        [
            '@type'      => 'WebPage',
            '@id'        => $page_canonical,
            'name'       => 'Privacy Policy',
            'url'        => $page_canonical,
            'description'=> $page_desc,
            'publisher'  => ['@type' => 'Organization', 'name' => SITE_NAME, 'url' => SITE_URL],
        ],
        [
            '@type' => 'BreadcrumbList',
            'itemListElement' => [
                ['@type' => 'ListItem', 'position' => 1, 'name' => 'Home', 'item' => SITE_URL . '/'],
                ['@type' => 'ListItem', 'position' => 2, 'name' => 'Privacy Policy', 'item' => $page_canonical],
            ],
        ],
    ],
], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);

require_once __DIR__ . '/includes/header.php';
require __DIR__ . '/includes/legal-hero.php';
?>

    <section class="section bg-cream">
      <div class="container">
        <div class="article-card reveal" style="max-width:900px;margin:0 auto;box-shadow:var(--shadow-sm);">
          <div class="article-body">

            <p style="font-size:0.875rem;color:var(--clr-text-secondary);margin-bottom:2rem;">
              <strong>Last updated:</strong> <?= h(LEGAL_UPDATED) ?>
            </p>

            <p>
              This Privacy Policy explains how <strong><?= h(SITE_NAME) ?></strong> (&ldquo;Fabloom&rdquo;,
              &ldquo;we&rdquo;, &ldquo;us&rdquo;) handles personal information collected through
              <a href="<?= SITE_URL ?>/"><?= h(preg_replace('~^https?://~', '', SITE_URL)) ?></a>.
              It applies to visitors who browse the site, send an enquiry, create an account or place an order.
            </p>
            <p>
              By using this website you agree to the practices described here. If you do not agree,
              please do not submit your details through the site.
            </p>

            <h2>1. Information we collect</h2>
            <p>We only ask for what an enquiry or an order actually needs.</p>
            <h3>Information you give us</h3>
            <ul>
              <li><strong>Enquiry and contact forms</strong> &mdash; your name, email address, phone number, company name (if given), the fabric or quantity you are asking about, and your message.</li>
              <li><strong>Orders and checkout</strong> &mdash; your name, email address, phone number, full shipping address, city, state, pincode and any delivery notes you add.</li>
              <li><strong>Account registration</strong> &mdash; your name, email address, phone number and a password, which is stored only as a one-way hash and is never readable by us.</li>
              <li><strong>Correspondence</strong> &mdash; the content of emails, WhatsApp messages and calls you send us about your enquiry or order.</li>
            </ul>
            <h3>Information collected automatically</h3>
            <ul>
              <li><strong>Server logs</strong> &mdash; your IP address, browser type, referring page and the time of the request. These are generated by our hosting provider and are used for security and troubleshooting.</li>
              <li><strong>Session cookie</strong> &mdash; a single cookie that keeps your shopping cart and login session working while you browse.</li>
            </ul>
            <p>
              We do not knowingly collect information from children under 18, and we do not ask
              for or store card numbers, CVV codes, UPI PINs or net-banking credentials on this website.
            </p>

            <h2>2. How we use your information</h2>
            <ul>
              <li>To answer your fabric enquiry and send you quotations, swatch details or price lists.</li>
              <li>To process, pack, dispatch and deliver your order, and to keep you updated on it.</li>
              <li>To manage your account, order history and saved addresses.</li>
              <li>To share the delivery name, address and phone number with our courier partner so your parcel can reach you.</li>
              <li>To maintain our own accounting, tax and dispatch records as required by Indian law.</li>
              <li>To detect and prevent fraud, spam submissions and misuse of the website.</li>
              <li>To send occasional updates about new fabrics or offers &mdash; only where you have asked for them. Every such message carries a way to opt out.</li>
            </ul>
            <p>We do not sell, rent or trade your personal information to anyone.</p>

            <h2>3. Who we share it with</h2>
            <p>Your details are shared only with parties who need them to complete your request:</p>
            <ul>
              <li><strong>Courier and logistics partners</strong>, to deliver your order.</li>
              <li><strong>Our web hosting and email providers</strong>, who store the site&rsquo;s data and deliver our notification emails.</li>
              <li><strong>Professional advisers and government authorities</strong>, where disclosure is required by law, a court order or a tax or regulatory obligation.</li>
            </ul>
            <p>
              These parties may only use the information for the purpose we share it for, and are
              expected to keep it confidential.
            </p>

            <h2>4. Cookies</h2>
            <p>
              This site uses a PHP session cookie. It carries no personal information &mdash; only a
              random identifier that lets the server remember your cart contents and, if you are
              signed in, your login. It expires when you close your browser or log out.
            </p>
            <p>
              Pages that embed a Google Map may set cookies from Google. Those are governed by
              Google&rsquo;s own privacy policy, not ours. You can block or delete cookies in your
              browser settings, but the cart and login will stop working if the session cookie is blocked.
            </p>

            <h2>5. How long we keep it</h2>
            <ul>
              <li><strong>Enquiries</strong> &mdash; up to 24 months from your last contact with us, so we can follow up on a pending quotation.</li>
              <li><strong>Orders and invoices</strong> &mdash; for the period required by Indian tax and accounting law, currently a minimum of eight years.</li>
              <li><strong>Account details</strong> &mdash; until you ask us to close the account.</li>
            </ul>

            <h2>6. Security</h2>
            <p>
              Data is transmitted over an encrypted HTTPS connection. Passwords are stored as
              salted one-way hashes, forms are protected against cross-site request forgery, and
              access to the admin panel and database is limited to authorised staff. No system on
              the internet can be guaranteed absolutely secure, so we cannot promise perfect
              security &mdash; but we will tell affected users without undue delay if a breach ever
              puts their data at risk.
            </p>

            <h2>7. Your rights</h2>
            <p>You may write to us at any time to:</p>
            <ul>
              <li>ask what personal information we hold about you;</li>
              <li>have inaccurate details corrected;</li>
              <li>have your data deleted, where we are not required to keep it for tax or legal reasons;</li>
              <li>withdraw consent to marketing messages;</li>
              <li>object to a particular use of your information.</li>
            </ul>
            <p>
              Send the request from the email address you gave us, to
              <a href="mailto:info@thefabloom.com">info@thefabloom.com</a>. We aim to respond within
              30 days. We may ask for proof of identity before acting on a deletion request.
            </p>

            <h2>8. Third-party links</h2>
            <p>
              Our site links to external pages, including our social media profiles and embedded
              maps. We do not control those sites and are not responsible for their content or
              their privacy practices. Read their policies before sharing information with them.
            </p>

            <h2>9. Changes to this policy</h2>
            <p>
              We may update this policy as our services or the law change. The revised version
              takes effect when it is published on this page, and the &ldquo;Last updated&rdquo;
              date above will change with it. Please review it from time to time.
            </p>

            <h2>10. Contact us</h2>
            <p>
              For any question about this policy or about your data:
            </p>
            <p>
              <strong><?= h(SITE_NAME) ?></strong><br>
              Mohiuddin Pur, Post&ndash;Habibpur, Bhagalpur, Bihar &ndash; 813113, India<br>
              Email: <a href="mailto:info@thefabloom.com">info@thefabloom.com</a><br>
              Phone: <a href="tel:+919760058796">+91 97600 58796</a>
            </p>

            <p style="margin-top:2.5rem;">
              See also our <a href="<?= SITE_URL ?>/terms-and-conditions">Terms &amp; Conditions</a>,
              <a href="<?= SITE_URL ?>/refund-policy">Refund &amp; Cancellation Policy</a> and
              <a href="<?= SITE_URL ?>/disclaimer">Disclaimer</a>.
            </p>

          </div>
        </div>
      </div>
    </section>

<?php require_once __DIR__ . '/includes/footer.php'; ?>
